baseURL = 'https://get-out.me/'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh-cn'
hasCJKLanguage = true
title = 'webee'
# 主题
theme = "get-started-it"
enableGitInfo = true
enableEmoji = true

[author]
name = "webee"
email = "webee.yw@gmail.com"
link = "https://get-out.me"

[params]
version = "0.3.X"
defaultTheme = "auto"
# public git repo url only then enableGitInfo is true
# 公共 git 仓库路径，仅在 enableGitInfo 设为 true 时有效
gitRepo = "https://github.com/webee/get-out.me"
# which hash function used for SRI, when empty, no SRI is used ("sha256", "sha384", "sha512", "md5")
# 哪种哈希函数用来 SRI, 为空时表示不使用 SRI ("sha256", "sha384", "sha512", "md5")
fingerprint = ""
enableServiceWorker = true

[params.search]
enable = true
type = "lunr"
# 文章内容最长索引长度
contentLength = 4000
# 搜索框的占位提示语
placeholder = ""
# 最大结果数目
maxResultLength = 10
#结果内容片段长度
snippetLength = 50
#搜索结果中高亮部分的 HTML 标签
highlightTag = "em"
#是否在搜索索引中使用基于 baseURL 的绝对路径
absoluteURL = false

# 页面头部导航栏配置
[params.header]
# 桌面端导航栏模式 ("fixed", "normal", "auto")
desktopMode = "fixed"
# 移动端导航栏模式 ("fixed", "normal", "auto")
mobileMode = "auto"

#页面头部导航栏标题配置
[params.header.title]
# LOGO 的 URL
logo = ""
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
pre = "<i class='fas fa-running'></i>"
# 标题名称
name = "webee"
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
post = ""
#是否为标题显示打字机动画
typeit = false

# 页面底部信息配置
[params.footer]
enable = true
#自定义内容 (支持 HTML 格式)
custom = ''
#是否显示 Hugo 和主题信息
hugo = true
#是否显示版权信息
copyright = true
#是否显示作者
author = true
# 网站创立年份
since = 2022
# ICP 备案信息，仅在中国使用 (支持 HTML 格式)
icp = ""
# 许可协议信息 (支持 HTML 格式)
license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

#Section (所有文章) 页面配置
[params.section]
# section 页面每页显示文章数量
paginate = 20
# 日期格式 (月和日)
dateFormat = "01-02"
# RSS 文章数目
rss = 10

# List (分类或标签) 页面配置
[params.list]
# list 页面每页显示文章数量
paginate = 20
# 日期格式 (月和日)
dateFormat = "01-02"
# RSS 文章数目
rss = 10

# 主页配置
[params.home]
#RSS 文章数目
rss = 10

# 主页个人信息
[params.home.profile]
enable = true
# Gravatar 邮箱，用于优先在主页显示的头像
gravatarEmail = "webee.yw@gmail.com"
# 主页显示头像的 URL
avatarURL = "/images/avatar.jpg"
#主页显示的网站标题 (支持 HTML 格式)
title = "webee's notes"
# 主页显示的网站副标题
subtitle = "待人以诚而去其诈，待人以宽而去其隘"
# 是否为副标题显示打字机动画
typeit = true
# 是否显示社交账号
social = true
#免责声明 (支持 HTML 格式)
disclaimer = ""

# 主页文章列表
[params.home.posts]
enable = true
# 主页每页显示文章数量
paginate = 6
#被 params.page 中的 hiddenFromHomePage 替代
# 当你没有在文章前置参数中设置 "hiddenFromHomePage" 时的默认行为
defaultHiddenFromHomePage = false

# 作者的社交信息设置
[params.social]
GitHub = "webee"
Email = "webee.yw@gmail.com"
RSS = true

# Page config
# 文章页面配置
[params.page]
# whether to hide a page from home page
# 是否在主页隐藏一篇文章
hiddenFromHomePage = false
# whether to hide a page from search results
# 是否在搜索结果中隐藏一篇文章
hiddenFromSearch = false
# whether to enable twemoji
# 是否使用 twemoji
twemoji = false
# whether to enable lightgallery
# 是否使用 lightgallery
lightgallery = false
# whether to enable the ruby extended syntax
# 是否使用 ruby 扩展语法
ruby = true
# whether to enable the fraction extended syntax
# 是否使用 fraction 扩展语法
fraction = true
# whether to enable the fontawesome extended syntax
# 是否使用 fontawesome 扩展语法
fontawesome = true
# whether to show link to Raw Markdown content of the content
# 是否显示原始 Markdown 文档内容的链接
linkToMarkdown = true
# whether to show the full text content in RSS
# 是否在 RSS 中显示全文内容
rssFullText = false

# Table of the contents config
# 目录配置
[params.page.toc]
# whether to enable the table of the contents
# 是否使用目录
enable = true
# whether to keep the static table of the contents in front of the post
# 是否保持使用文章前面的静态目录
keepStatic = false
# whether to make the table of the contents in the sidebar automatically collapsed
# 是否使侧边目录自动折叠展开
auto = true

# Code config
# 代码配置
[params.page.code]
# whether to show the copy button of the code block
# 是否显示代码块的复制按钮
copy = true
# the maximum number of lines of displayed code by default
# 默认展开显示的代码行数
maxShownLines = 25

# Social share links in post page
# 文章页面的分享信息设置
[params.page.share]
enable = true
Twitter = true
Facebook = true
Linkedin = false
Whatsapp = false
Pinterest = false
Tumblr = false
HackerNews = true
Reddit = false
VK = false
Buffer = false
Xing = false
Line = true
Instapaper = false
Pocket = false
Digg = false
Stumbleupon = false
Flipboard = false
Weibo = true
Renren = false
Myspace = false
Blogger = false
Baidu = false
Odnoklassniki = false
Evernote = false
Skype = false
Trello = false
Mix = false

# 评论系统设置
[params.page.comment]
enable = true

# Valine 评论系统设置
[params.page.comment.valine]
enable = true
appId = "LRac7zTTMerOeNuohS6pRxcw-gzGzoHsz"
appKey = "wtf0A3jmx2acmG06BrHMs3Vb"
placeholder = "说点什么吧！"
avatar = ""
meta = ""
pageSize = 10
lang = ""
visitor = true
recordIP = true
highlight = true
enableQQ = false
serverURLs = ""
# emoji 数据文件名称, 默认是 "google.yml"
# ("apple.yml", "google.yml", "facebook.yml", "twitter.yml")
# 位于 "themes/LoveIt/assets/data/emoji/" 目录
# 可以在你的项目下相同路径存放你自己的数据文件:
# "assets/data/emoji/"
emoji = ""

# TypeIt 配置
[params.typeit]
# 每一步的打字速度 (单位是毫秒)
speed = 150
# 光标的闪烁速度 (单位是毫秒)
cursorSpeed = 1000
# 光标的字符 (支持 HTML 格式)
cursorChar = "|"
# 打字结束之后光标的持续时间 (单位是毫秒, "-1" 代表无限大)
duration = -1

[menu]

[[menu.main]]
identifier = "posts"
pre = ""
name = "所有文章"
post = ""
url = "/posts/"
title = ""
weight = 1

[[menu.main]]
identifier = "tags"
pre = ""
name = "标签"
post = ""
url = "/tags/"
title = ""
weight = 2

[[menu.main]]
identifier = "categories"
pre = ""
name = "分类"
post = ""
url = "/categories/"
title = ""
weight = 3

[[menu.main]]
identifier = "about"
pre = ""
name = "关于"
post = ""
url = "/about/"
title = ""
weight = 4

[markup]

[markup.highlight]
noClasses = false

# Options to make output .md files
# 用于输出 Markdown 格式文档的设置
[mediaTypes]

[mediaTypes."text/plain"]
suffixes = ["md"]

# Options to make output .md files
# 用于输出 Markdown 格式文档的设置
[outputFormats.MarkDown]
mediaType = "text/plain"
isPlainText = true
isHTML = false

# 用于 Hugo 输出文档的设置
[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML", "MarkDown"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
taxonomyTerm = ["HTML"]
